language: generic
dist: xenial
services:
- docker
env:
  global:
  - OWLRL_VERSION="5.2.0"
  - PYBUILD_DISABLE=test
  - secure: EJCRSbrtmNbFP1caJjzEZlGFb8oVqmUtcfreapnkW+2NC9XmkQZbPFHmN3PCrUBwp77mqM3AU2Vj0/qXTFsX4XJYxd8Ml2l8jvtcZbli/TmRo2TWZ0k/j/IJ41R9XLj9KWvKmh046s/qivyO3cBJpV6uZ6heQybQ29x+o5VTAcP58A84Q4K646gdviWnATs5g/cz9cCqqMesHvmnuXB7rxcmt+uPgYk7PiaiVH8zw2VmMmzO/I4Gj9Voome9WF8oBU4Tz1LAqLQYlBAxnCKkqiOImbXfVOghpdxvLSflIzR1Q89xuxJN5TYenPyTeBJY5705hcftm7qF6LyH8z4EQQK744yJkfPHmtOp0PcMI9p0GndtkNN5erPMtuOoHBh0LYPiI/JwBmtCgjQl9SoUzNruxTIVh1mdgT0hmeBs/aXHuc0rMFf0YZwJ8DmuJiw9vNov6E93dpbRhcFojgB/uvgAj++BfP9gTpQQ8HNGnsB5oyTU9u8OIPMPA1arzK7kvan4ZoZ3VDQhC6SIFqv/4FCjNbmmy/cI3Yx/gRyuiAsEjcJuy3ry6ur9iPOQbOD4SmrYpsQ+/HEMNZMAMUEYYtSoqmQeMu2c006M6Uth/Hhgl5JryXWuy0R8K83Jgi+fB3oS686ekV7ziGfTPiSG01SfMitKj0zJxJHkFVfjUCY=
  matrix:
  - DEBIAN_VERSION=jessie OWLRL_BUILD=debian-8 STDEB3_SIGN_RESULTS=0 STDEB3_EXTRA_ARGS="--x-python3-version=\">=3.4\"" BUILD_DEPS="python3-rdflib python3-pytest"
  - DEBIAN_VERSION=stretch OWLRL_BUILD=debian-9 STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=10.2.5 --dh-compat=10 --deb-standards-vers=4.1.4" BUILD_DEPS="python3-rdflib python3-rdflib-jsonld python3-pytest"
  - DEBIAN_VERSION=buster OWLRL_BUILD=unknown STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=11.5.2 --dh-compat=11 --deb-standards-vers=4.3.0" BUILD_DEPS="python3-rdflib python3-rdflib-jsonld python3-pytest"
  - DEBIAN_VERSION=xenial OWLRL_BUILD=ubuntu-16.04 STDEB3_SIGN_RESULTS=0 STDEB3_EXTRA_ARGS="--dh-min=9.20160115ubuntu3 --dh-compat=9" BUILD_DEPS="python3-rdflib python3-rdflib-jsonld python3-pytest"
  - DEBIAN_VERSION=bionic OWLRL_BUILD=ubuntu-18.04 STDEB3_SIGN_RESULTS=1 STDEB3_EXTRA_ARGS="--dh-min=11.1.6 --dh-compat=11 --deb-standards-vers=4.1.4" BUILD_DEPS="python3-rdflib python3-rdflib-jsonld python3-pytest"
before_install:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export REPO=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_REPO_SLUG;
  else echo $TRAVIS_PULL_REQUEST_SLUG; fi)
- echo "REPO=$REPO, TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- openssl aes-256-cbc -K $encrypted_d13667eb3d75_key -iv $encrypted_d13667eb3d75_iv
  -in secret_key.asc.enc -out /tmp/secret_key.asc -d
- mkdir -p /tmp/output
- chmod 777 /tmp/output
- docker pull ashleysommer/stdeb3:$DEBIAN_VERSION
- echo "from ashleysommer/stdeb3:$DEBIAN_VERSION" > ./Dockerfile.deploy
- echo "USER root" >> ./Dockerfile.deploy
- echo "RUN apt-get install -y curl ${BUILD_DEPS}" >> ./Dockerfile.deploy
- if [ "${DEBIAN_VERSION}" = "jessie" ]; then echo "RUN curl -L http://http.us.debian.org/debian/pool/main/p/python-rdflib-jsonld/python3-rdflib-jsonld_0.4.0-2~bpo8+1_all.deb -o python3-rdflib-jsonld_0.4.0-2~bpo8+1_all.deb" >> ./Dockerfile.deploy; fi
- if [ "${DEBIAN_VERSION}" = "jessie" ]; then echo "RUN curl -L http://http.us.debian.org/debian/pool/main/r/rdflib/python3-rdflib_4.2.1-2~bpo8+1_all.deb -o python3-rdflib_4.2.1-2~bpo8+1_all.deb" >> ./Dockerfile.deploy; fi
- if [ "${DEBIAN_VERSION}" = "jessie" ]; then echo "RUN dpkg --install python3-rdflib_4.2.1-2~bpo8+1_all.deb python3-rdflib-jsonld_0.4.0-2~bpo8+1_all.deb" >> ./Dockerfile.deploy; fi
- echo "RUN curl -L https://github.com/ashleysommer/OWL-RL/releases/download/v${OWLRL_VERSION}-deb/python3-owlrl_${OWLRL_VERSION}-1_all+${OWLRL_BUILD}.deb -o python3-owlrl_${OWLRL_VERSION}-1_all+${OWLRL_BUILD}.deb" >> ./Dockerfile.deploy
- echo "RUN dpkg --install python3-owlrl_${OWLRL_VERSION}-1_all+${OWLRL_BUILD}.deb" >> ./Dockerfile.deploy
- echo "USER stdeb3" >> ./Dockerfile.deploy
- docker build -t temp_image -f ./Dockerfile.deploy .
before_script:
- docker run -v /tmp/secret_key.asc:/tmp/secret_key.asc -e PYTHON_PROJECT_GIT="https://github.com/${REPO}.git"
  -e PYTHON_PROJECT_BRANCH="${BRANCH}" -v /tmp/output:/home/stdeb3/output -e GPG_SECRET_KEY="/tmp/secret_key.asc"
  -e GPG_SECRET_KEY_PASSPHRASE="${GPG_SECRET_KEY_PASSPHRASE}" -e STDEB3_SIGN_RESULTS="$STDEB3_SIGN_RESULTS"
  -e STDEB3_EXTRA_ARGS="$STDEB3_EXTRA_ARGS" -e PYBUILD_DISABLE="$PYBUILD_DISABLE" -t -i temp_image
- ls -lah /tmp/output
deploy:
  provider: releases
  api_key:
    secure: C1Lrl5L+d++qUVb5UDWhNakQJ7pPu76x/ZA5iiSnAwLBTO8BVuQCQ7C5bAdI8XIQUZbzAREmcR98pYtZq5ir83Piy/O/XHriLy5KdjNBbI2CdhjjAcX4wwwRzAdqcZHsH4MuwUJADufCxSi6jAKMjXacgF74G5+Lq6ntR5oait39fE73/kp54bFsq1zYJY7rjF980vQQq6sdrnS0NQ1mMgweLNmoFBfNFPDVQZgXliie4v9LCfqj08CQ0MksESa0UBOoce8MRDShh7voDA/lpEFKNcutd9ARmNexlogKb6Po58sx0PNTA9fP8hmvHPxy1/GFH5zW70EOn1ts9p7bqrW3gBK+LNgimNPbdpqE/EL/d2rvGnrR/tuqgDC1rAnEmgy0sfS5T/eszYxs6MXyzq4d3jMpXGS6vhTQMMa1TpxpWSbK9I8WFBSPnyVuPkIsXBO4wJe0+EpT7+ufxDxVeBKyzVTgNDjvIoEFgQUCB43E1vQgSHB18nd1i8RRfwG57u4PY2Tt+NMw4U2+npP/ozak2LuZHsmVz98uK7Mukd/NhsWhiIjidbz9jsgO4MrWUBDl3HQgjSV+D6Jgi0naRq296Fya2BEYZejwnvtL9WDNZK8RdCOKj2IVH/lueAVcStwLT1fp3jzskZCGjzpWbXhtSEsVKws993dpDtlMXLE=
  overwrite: true
  file_glob: true
  file: "/tmp/output/*.deb"
  skip_cleanup: true
  on:
    branch: debian
    tags: true
